CODEOWNERS

Add Core Leads into Codeowners for break-glass overrides on PRs
This is a temporary measure, effectively some training wheels until the HiLUX team are showing consistent & reliable PRs, at which point the HiLUX FE team will be added with merge permissions.
This is keeping mind of the balance between HiLUX gifting improvments, but Orange being responsible for support.

BAU: Add core-leads as break-glass in CODEOWNERS

---

.github/workflows/post-merge-to-build.yml
.github/workflows/pre-merge-to-dev.yml
.gitignore

- Updated post-merge workflow to use devplatform-upload-action-ecr@1.2.0
- Updated .gitignore
- Required for canary deployments across Identity
- [IPS-493](https://govukverify.atlassian.net/browse/IPS-493)
- [IPS-532](https://govukverify.atlassian.net/browse/IPS-532)
- Image successfully pushed to dev, with commit tag:
https://github.com/govuk-one-login/ipv-cri-kbv-hmrc-front/actions/runs/7930584278
[IPS-493]: https://govukverify.atlassian.net/browse/IPS-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-532]: https://govukverify.atlassian.net/browse/IPS-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-493: Update post-merge workflow to use devplatform-upload-action-ecr

---

src/app/kbv/controllers/load-question.js
src/app/kbv/controllers/single-amount-question.js
src/app/kbv/steps.js
tests/browser/features/happy.feature
tests/browser/pages/enter-ni-payslip.js
tests/browser/pages/index.js
tests/browser/pages/single-amount-question.js
tests/browser/step_definitions/enter-ni-payslip.js
tests/imposter/private-api-config.yaml
tests/unit/src/app/kbv/controllers/load-question.test.js
tests/unit/src/app/kbv/controllers/single-amount-question.test.js

Set up ability to define routes for each question page, sharing the same underlying controller/template.
A UCD requirement is that we serve each question page under a distinct url path (as provided by them) - we need a mechanism for defining routes for each question page while sharing a single controller/template and mapping question keys to url paths.
- [PYIC-5161](https://govukverify.atlassian.net/browse/PYIC-5161)
[PYIC-5161]: https://govukverify.atlassian.net/browse/PYIC-5161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-5161: set up url path routing for question pages

---

package-lock.json
package.json

We are temporarily downgrading hmpo-components
It was decided that for now and to unblock our tickets that we revert to an earlier version of hmpo-components and just use the plain text input field until the above PR gets merged.
We made a change in hmpo-components to add the prefix field to the text inputs, however this change made it a required field and therefore cant use the input field without a prefix There is a current PR https://github.com/HMPO/hmpo-components/pull/165 to fix this issue which is awaiting merge from HMPO
- [PYIC-4652](https://govukverify.atlassian.net/browse/PYIC-4652)
[PYIC-4652]: https://govukverify.atlassian.net/browse/PYIC-4652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-4652: Downgrade hmpo-components

---

src/app/kbv/controllers/load-question.js
src/app/kbv/steps.js
src/locales/cy/fields.yml
src/locales/cy/pages.yml
src/locales/en/fields.yml
src/locales/en/pages.yml
src/views/kbv/single-amount-question.njk
tests/browser/features/happy.feature
tests/browser/pages/enter-4-digits-bank-account-tax-credits.js
tests/browser/pages/index.js
tests/browser/step_definitions/enter-4-digits-bank-account-tax-credits.js
tests/imposter/data/questions.json
tests/imposter/private-api-config.yaml

URL path: /enter-4-digits-bank-account-tax-credits
Question key: ita-bankaccount
Create the page, add context along with welsh translations Added to the question key map and grouped with singleAmountQuestion Added steps to create the happy path browser test for bankAccount questions
(when [hmpo-components PR](https://github.com/HMPO/hmpo-components/pull/165) gets merged the prefix will be an optional field. There is a separate PR to [downgrade hmpo-components](https://github.com/govuk-one-login/ipv-cri-kbv-hmrc-front/pull/116) for now which will revert this to a plain text input field)
Users need to be able to enter last 4 digits from a particular bank account in order for HMRC to validate that user is who they say they are.
- [PYIC-4652](https://govukverify.atlassian.net/browse/PYIC-4652) …

PYIC-4652: Add Tax credits question page

---

src/app/kbv/controllers/load-question.js
src/app/kbv/controllers/single-amount-question.js
src/app/kbv/steps.js
src/locales/cy/fields.yml
src/locales/cy/pages.yml
src/locales/en/fields.yml
src/locales/en/pages.yml
src/presenters/index.js
src/presenters/question-to-details.js
src/presenters/question-to-inset.js
src/utils/tax-year-to-range.js
src/views/kbv/single-amount-question.njk
tests/browser/features/happy.feature
tests/browser/pages/enter-total-for-year-p60.js
tests/browser/pages/index.js
tests/browser/step_definitions/enter-total-for-year-p60.js
tests/imposter/data/questions.json
tests/imposter/private-api-config.yaml
tests/unit/src/presenters/question-to-details.test.js
tests/unit/src/presenters/question-to-inset.test.js
tests/unit/src/utils/tax-year-to-range.test.js

URL path: /enter-total-for-year-p60
Question key: rti-p60-payment-for-year
Added content along with welsh translations
Added a new presenter for the details object along with test suite 
Add a new utils file to help translate currentTaxYear to the correct format needed along with test suite
Added to the question key map and grouped with singleAmountQuestion 
Added steps and actions for a new browser test, p60-journey
Users need to be able to enter details from their P60 so HMRC can validate that the user is who they say they are.
- [PYIC-4670](https://govukverify.atlassian.net/browse/PYIC-4670)
[PYIC-4670]: https://govukverify.atlassian.net/browse/PYIC-4670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-4670: Add P60 question page - Total for year amount

---

src/app/kbv/controllers/load-question.js
src/app/kbv/controllers/single-amount-question.js
src/app/kbv/steps.js
src/locales/cy/fields.yml
src/locales/cy/pages.yml
src/locales/en/fields.yml
src/locales/en/pages.yml
src/presenters/question-to-content.js
src/presenters/question-to-inset.js
src/utils/tax-credits-months.js
tests/browser/features/happy.feature
tests/browser/pages/enter-recent-tax-credits-payment.js
tests/browser/pages/index.js
tests/browser/step_definitions/enter-recent-tax-credits-payment.js
tests/imposter/data/questions.json
tests/unit/src/presenters/question-to-content.test.js
tests/unit/src/presenters/question-to-inset.test.js
tests/unit/src/utils/text-credits-months.test.js

URL path: /enter-recent-tax-credits-payment
Question key: tc-amount
Add context along with welsh translations
Add to the question key map and grouped with taxCredits 
Add steps to create the happy path browser test for taxCredits questions 
Pulled out logic from question-to-inset into a utils function which is still called inside inset but can also be used elsewhere Added new taxCreditsMonths function to question-to-content for when dynamicDate is used with the content translations
As a user I want to enter information from my tax credits payments so that I can prove my identity
- [PYIC-4655](https://govukverify.atlassian.net/browse/PYIC-4655)
[PYIC-4655]: https://govukverify.atlassian.net/browse/PYIC-4655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS …

PYIC-4655: Add 'recent tax credits' question page

---

tests/browser/features/happy.feature
tests/browser/features/prove-identity-another-way.feature
tests/docker/compose.yml
tests/imposter/private-api-config.yaml
tests/imposter/scripts/get-question.groovy
tests/imposter/scripts/post-answer.groovy

NOTE Only one (or neither) of this and https://github.com/govuk-one-login/ipv-cri-kbv-hmrc-front/pull/175 should be merged. These both solve the same problem in different ways.
Update imposter configuration so that question journeys are more generic and tests can be run multiple times without restarting the imposter server
This sets up imposter configuration so that all question journeys are handled by the same handlers using regexes.
Each test gets a unique session ID so it gets a unique question and answer store and doesn't clash with itself or other tests when run multiple times.
The imposter tests only work once before you have to restart the imposter server to reset the question and answer stores.
- [PYIC-5705](https://govukverify.atlassian.net/browse/PYIC-5705)
[PYIC-5705]: …

PYIC-5705: Generic imposter config

---

src/app/kbv/controllers/single-amount-question.js
src/app/kbv/fields.js
src/app/kbv/fieldsHelper.js
src/app/kbv/steps.js
src/locales/cy/fields.yml
src/locales/en/fields.yml
tests/browser/features/validation.feature
tests/browser/pages/answer-p60-questions.js
tests/browser/step_definitions/answer-p60-questions.js
tests/unit/src/app/kbv/controllers/single-amount-question.test.js
tests/unit/src/app/kbv/fieldsHelper.test.js

Added initial validation to make sure user cant submit anything other than integers, or decimal if only containing .0 .00 etc Once initial validation passes in the saveValues is a switch statement which matches to a questionKey, two new functions are called to strip any whitespace and strip any decimals Added translations
Added new tests for the controller
Added new tests for the two functions
The initial validation regex: 
- Zero or more whitespace characters at the beginning.
- One or more digits.
- An optional group consisting of zero or more whitespace characters, a dot, zero or more whitespace characters, and one or more 0 characters.
- Zero or more whitespace characters at the end.
It will match strings like "123", "123.00", "123.0", "123 . 00", etc.
- …

PYIC:4920: Validation - Amounts with pounds only and Welsh translations

---

.github/pull_request_template.md
CODEOWNERS

Updated permissions, PR templates and Deployments to align to Lime
To simplify the management of the repo by the Lime team
- [LIME-1076](https://govukverify.atlassian.net/browse/LIME-1076)
[LIME-1076]: https://govukverify.atlassian.net/browse/LIME-1076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1076: Moving repo permissions and deployment from Orange to Lime

---

package-lock.json
package.json
src/app/kbv/controllers/single-amount-question.js
src/locales/cy/fields.yml
src/locales/en/fields.yml
src/views/kbv/single-amount-question.njk

Define the £ prefix at the field level and explicitly set "" for fields where we don't want the prefix to display
This gets around the issue of the prefix always displaying (for which we've raised a PR in hmpo-components: https://github.com/HMPO/hmpo-components/pull/165) so we have a workaround in place while waiting for the PR to be merged and released
- [PYIC-6421](https://govukverify.atlassian.net/browse/PYIC-6421)
[PYIC-6421]: https://govukverify.atlassian.net/browse/PYIC-6421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-6421 Workaround for prefix issue

---

src/app/kbv/fields.js
src/locales/cy/fields.yml
src/locales/en/fields.yml
tests/browser/features/validation.feature
tests/browser/pages/pensions-benefits-self-assessment.js
tests/browser/pages/pensions-benefits-short-tax-return.js
tests/browser/step_definitions/pension-self-assessment.js

The validation rules that must apply to each question set:
- User does not enter anything
- User enters disallowed characters
- Strip out spaces, should strip out the .00
Add error content with welsh translations
Add browser tests for Self Assessment validation
As a user, 
I want to be guided through the KBV questions with clear validations in place, 
So that I can prove my identity without making mistakes
- [PYIC-5182](https://govukverify.atlassian.net/browse/PYIC-5182)
[PYIC-5182]: https://govukverify.atlassian.net/browse/PYIC-5182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-5182: Validation - Self assessment question page in pounds only 

---

package.json

BAU Use npm over yarn
The build assets scripts were still using yarn but this repo should be using npm only now

BAU Use npm over yarn

---

src/app/kbv/controllers/self-assessment-question.js
src/app/kbv/controllers/self-assessment-router.js
src/app/kbv/controllers/single-amount-question.js
src/app/kbv/fields.js
src/app/kbv/steps.js
src/locales/cy/fields.yml
src/locales/cy/pages.yml
src/locales/en/fields.yml
src/locales/en/pages.yml
src/presenters/question-to-content.js
src/presenters/question-to-details.js
src/presenters/question-to-inset.js
src/presenters/question-to-title.js
src/utils/tax-year-to-range.js
src/views/kbv/answer-security-questions.njk
src/views/kbv/single-amount-question.njk
tests/imposter/data/questions.json
tests/unit/src/app/kbv/controllers/self-assessment.router.test.js
tests/unit/src/presenters/question-to-content.test.js
tests/unit/src/presenters/question-to-details.test.js
tests/unit/src/presenters/question-to-inset.test.js
tests/unit/src/presenters/question-to-title.test.js
tests/unit/src/utils/tax-year-to-range.test.js

From HMRC guidance, in some cases a user may be able to use their P60 from either of the previous two tax years (rather than only the previous tax year) to answer a question.
We will expect a back-end response with the 2 tax years:
```{
"info": {
"currentTaxYear": "2022/23",
"previousTaxYear": "2021/22" // ** new **
}
}
```
Added the ability to handle previousTaxYear, if this doesnt exist the existing fucntionality stays the same and it checks for only currentTaxYear
Aligned content to display the same across views as there was slight variations on how we was doing it
Added welsh translations for the updated content
Added test cases to cover new functionality
As a user
I want to enter information from my P60 using the correct years
So that I can prove my identity
- …

PYIC-4915: Passing tax year(s) 

---

src/app/kbv/controllers/start.js
src/app/kbv/steps.js
src/lib/config.js
tests/browser/features/insufficient-questions.feature
tests/browser/step_definitions/relying-party.js
tests/imposter/private-api-config.yaml
tests/imposter/private-api.yaml
tests/unit/src/app/kbv/controllers/start.test.js

Call the API `/fetchquestions` endpoint at the start of journey, on post of the root entry point which proceeds to the 'answer-security-questions' start page. Note this just adds the API call for now, but we will likely need to add a loading 'spinner' page pending UCD ([PYIC-4649](https://govukverify.atlassian.net/browse/PYIC-4649)).
This call is required to prime the questions set on the backend and ensure there are sufficient questions for the provided NINO - if there are sufficient questions it will return a 2xx response and we can continue, if there are not it will return a 4xx error response with oauth code `invalid_request` which we should let bubble up to the error handler to be returned to the client.
- [PYIC-6856](https://govukverify.atlassian.net/browse/PYIC-6856)
[PYIC-4649]: …

PYIC-6856 Call /fetchquestions at start of journey

---

src/lib/config.js
src/presenters/question-to-content.js
src/presenters/question-to-inset.js
tests/imposter/data/questions.json
tests/unit/src/presenters/question-to-content.test.js
tests/unit/src/presenters/question-to-inset.test.js

Hardcode dynamic payslip dates as (today-3months) for now
The HMRC API doesn't actually provide info.months for payslips questions, so as a quick fix we'll hardcode the 'use payslip dated before X' dates for now
- [PYIC-7106](https://govukverify.atlassian.net/browse/PYIC-7106)
[PYIC-7106]: https://govukverify.atlassian.net/browse/PYIC-7106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-7106 Make dynamic dates hardcoded for now

---

src/locales/cy/pages.errors.yml
src/locales/en/pages.errors.yml
src/views/errors/error.njk
src/views/errors/page-not-found.njk
src/views/errors/session-ended.njk

Used the correct keys in the templates and add missing locals keys
Title/content for the error pages in HMRC KBVs FE not rendering content correctly, specifically error.njk, page-not-found.njk and session-ended.njk. 
- [PYIC-7151](https://govukverify.atlassian.net/browse/PYIC-7151)
[PYIC-7151]: https://govukverify.atlassian.net/browse/PYIC-7151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-7151: Error pages correctly render title and page content

---

deploy/template.yaml

Stage 1 of 2 for enabling ECS Canaries (Stage 2 is [here](https://github.com/govuk-one-login/ipv-cri-kbv-hmrc-front/pull/313))
Added the ECSCanaryDeployment nested Stack to handle Blue/Green ECS deployments
Assumption made that we will always want to have Canary infrastructure in place (even if deployment strategy is AllAtOnce)
Canary deployments provide extra safety measures when rolling out new application image versions
https://govukverify.atlassian.net/browse/IPS-536

IPS-554/kbv hmrc ecs canary

---

deploy/template.yaml

Stage 2 of 2 for enabling ECS Canaries (Stage 1 is [here](https://github.com/govuk-one-login/ipv-cri-kbv-hmrc-front/pull/312))
This is a fairly arbitrary change to trigger the deployment process, but removes some now-unused ECS config.
Canary deployments provide extra safety measures when rolling out new application image versions
https://govukverify.atlassian.net/browse/IPS-554
AllAtOnce rollout tested in `-dev`:

IPS-554/kbv hmrc ecs canary stage 2

---

deploy/template.yaml

Update template env var to enable Welsh toggle in all envs
It's currently disabled in deployed envs
- [PYIC-7218](https://govukverify.atlassian.net/browse/PYIC-7218)
[PYIC-7218]: https://govukverify.atlassian.net/browse/PYIC-7218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-7218 Enable Welsh toggle in all envs

---

deploy/template.yaml

- Updated auto scaling to to have a max capacity of 60 (for performance)

LIME-1238 - Updating ECS autoscaling to have a max capacity of 60

---

deploy/template.yaml

Updated scaling policies
To align with other CRIs and enable further perf testing while autoscaling is still being finalised across the program

LIME-1097: Aligning scaling policy with other Lime CRIs to enable perf testing

---

src/app/kbv/controllers/self-assessment-payment-question.js
tests/unit/src/app/kbv/controllers/self-assessment-payment-question.test.js

LIME-1248 SA payment detail userInput amended
SA payment details userInput amended - key names amended and 'amount' value converted to number from string.
To fit HMRC requirements re data type and key names of this data.
- [LIME-1248](https://govukverify.atlassian.net/browse/LIME-1248)
Related PR has already been merged for the https://github.com/govuk-one-login/ipv-third-party-stubs/pull/238 to remove a troublesome space from in front of the amount for user AL000000S to ensure third-party-stub test users are now in keeping with the format expected by HMRC. This has been confirmed by testing user journeys with the minor third-party-stub change and this FE change.
[LIME-1248]: https://govukverify.atlassian.net/browse/LIME-1248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …

LIME-1248 SA payment detail userInput amended

---

package-lock.json
package.json
tests/browser/.env.example
tests/browser/README.md
tests/browser/environment-variables.md
tests/browser/support/setup.js

- "@aws-sdk/client-dynamodb": "3.654.0",
- "express": "4.21.0",
- "nodemon": "3.1.5",
- "uglify-js": "3.19.3"
- Enable browser tests to run in parallel
- Dependabot
- Keeping up-to-date with package updates
- [PYIC-7260](https://govukverify.atlassian.net/browse/PYIC-7260)
[PYIC-7260]: https://govukverify.atlassian.net/browse/PYIC-7260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-7260: Update packages according to dependabot

---

src/app/kbv/fields.js
src/app/kbv/steps.js
src/lib/config.js
tests/browser/step_definitions/enter-4-digits-bank-account-tax-credits.js

Remove `maxlength` attributes from text inputs
Accessibility
- [PYIC-7357](https://govukverify.atlassian.net/browse/PYIC-7357)
[PYIC-7357]: https://govukverify.atlassian.net/browse/PYIC-7357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PYIC-7357: Remove maxlength attributes from text boxes

---

deploy/template.yaml

Remove DesiredCount as its now controlled by autoscaling
Stack fails to deploy due to the value already existing.
- [LIME-1238](https://govukverify.atlassian.net/browse/LIME-1238)
[LIME-1238]: https://govukverify.atlassian.net/browse/LIME-1238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1238 Remove DesiredCount as its now controlled by autoscaling

---

deploy/template.yaml

Renamed ECSAutoScaling target to match naming of convention of existing AWS resource (negating the need for manual deletion of resource)

LIME-1238 - Renaming ECSAutoScaling to match existing resource name

---

.secrets.baseline
deploy/template.yaml
package-lock.json

Ensure log groups are all set to 30 days retention
To ensure log groups do not have extended retention lengths
- [LIME-1169](https://govukverify.atlassian.net/browse/LIME-1169)
[LIME-1169]: https://govukverify.atlassian.net/browse/LIME-1169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1169 Set log group retention in days to 30 for all log groups

---

package-lock.json

Bumped version of the `cookie-parser` package
It depended on v0.4.1 of the `cookie` package which has a security issue: https://github.com/govuk-one-login/ipv-cri-kbv-hmrc-front/security/dependabot/21

BAU: Update cookie-parser npm package to update it's dependency on cookie v0.4.1 which has a security issue

---

deploy/template.yaml

Changed health check values for HealthCheckTimeoutSeconds and HealthCheckIntervalSeconds
To match recommended values on ADR140
- [LIME-1316](https://govukverify.atlassian.net/browse/LIME-1316)
[LIME-1316]: https://govukverify.atlassian.net/browse/LIME-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1316 Align health check with ADR140

---

tests/imposter/private-api-config.yaml

The mock endpoint for `/authorization` has a short-circuit condition if it detects that the session ID matches a particular 'abandon' pattern.
Ports the mock code for the `/authorization` abandon condition from JavaScript to Groovy.
This condition was written in JavaScript, but the remainder of the mock's scripts are written in Groovy.
- None
None
- ~Update [README](./blob/main/README.md) with any new instructions or tasks~ N/A
✅ Abandon condition should match
✅ Returns valid JSON
```shell
$ curl http://localhost:8080/authorization -H 'session-id: questions-abandon-SEPARATOR-foo'
{"redirect_uri":"http://example.net","oauth_error":{"error_description":"access-denied","error":"access_denied"}}
```
✅ Abandon condition should not match
✅ Default response should be returned
```shell
$ curl …
```

refactor(mock): ports abandon script to Groovy.

---

.github/workflows/post-merge-to-build.yml
.github/workflows/pre-merge-to-dev.yml
.pre-commit-config.yaml
deploy/template.yaml

- Add SAM validate lint on pre and post merge checks
The following change was required to pass the new linting steps:
- Create condition for `HealthCheckGracePeriodSeconds` (this Property is only used if canaries are disabled ie if the service is using a load balancer and not managed by CodeDeploy). This was to fix `E3056 | ECS service using HealthCheckGracePeriodSeconds must also have LoadBalancers specified` [E3056](https://github.com/aws-cloudformation/cfn-lint/blob/main/src/cfnlint/rules/resources/ecs/ServiceHealthCheckGracePeriodSeconds.py) See the docs at:
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html
- https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3821732161/ECS+-+Canary+Deployments+Migration+Guidance
- Code Quality …

IPS-1132: Add linting

---

deploy/template.yaml

Template.yaml updated as part of decommissioning of HMRC KBV to reduce maintenance costs. 
ECS Autoscaling min and max set to one in dev to still allow for testing and set to 0 in all other environments. CPU and memory set to minimum possible for dev and 0 for all other environments. Unnecessary alarms disabled.
- [LIME-1465](https://govukverify.atlassian.net/browse/LIME-1465)
- **Showing what will happen in dev**
I added the dev environment to the 'IsPerformance' condition and deployed to dev to test my changes. 
&nbsp;
**- Evidence min and max container value is working:**
&nbsp;
- **Evidence CPU and memory amended:**
post changes:
&nbsp;
&nbsp;
pre-changes:
&nbsp;
- **One container running:**
----------------------------------------------------------------------------------------------- …

LIME-1465 updates ECS configuration for decom

---

deploy/template.yaml

This is protected by a specific WAF for CloudFront
Added tags to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
Added tags
to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
https://govukverify.atlassian.net/browse/IPS-1407

Update to  exclude the origin load balancer from the regional FMS policy
