tests/imposter/private-api-config.yaml
Update failure scenarios to match other repositories
=> fix: Use shortened names for error scenarios

.github/workflows/unit-tests.yml
Run unit tests workflow on merge to `main`
=> feat(fe): Run unit tests GHA on main

jest.config.js, package-lock.json, package.json, src/app/kbv/controllers/load-question.js, src/app/kbv/steps.js, src/lib/config.js, tests/imposter/private-api-config.yaml, tests/unit/lib/helpers.js, tests/unit/src/app/kbv/controllers/load-question.test.js
Add insufficient questions flow as the question based flow in the CRI
=> Oj 1872/insufficient questions

.github/workflows/post-merge-to-build.yml, .github/workflows/post-merge-to-dev.yml
post merge push to dev and  build workflows
The workflows were missing
=>  add missing workflows

deploy/template.yaml
Added a `template.yaml` for deploying the KBV HMRC Front repo. This was missing.
=> Bau add template yaml

.github/workflows/post-merge-to-build.yml
Update build deployment workflow
devplatform upload action had incorrect name
To fix the deployments
=> BAU workflow action name correction

.secrets.baseline, deploy/template.yaml
Updated `template.yaml` to have Dynatrace integration.
The work done here is a duplication of the work done in [ipv-cri-check-hmrc-front](https://github.com/govuk-one-login/ipv-cri-check-hmrc-front/pull/12)
- [OJ-2110](https://govukverify.atlassian.net/browse/OJ-2110)
- [IPS-286](https://govukverify.atlassian.net/browse/IPS-286)
- [IPS-424](https://govukverify.atlassian.net/browse/IPS-424)
[OJ-2110]: https://govukverify.atlassian.net/browse/OJ-2110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OJ-286]: https://govukverify.atlassian.net/browse/OJ-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-424]: https://govukverify.atlassian.net/browse/IPS-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
=> OJ-2110: Added dynatrace layer (IPS-286)

.secrets.baseline, deploy/template.yaml
template.yaml
Fix syntax and incorrectly formatted dynatrace section
=> BAU: Fix Dynatrace

.eslintignore, .eslintrc.js, .github/workflows/pre-commit.yml, .github/workflows/unit-tests.yml, .pre-commit-config.yaml, .prettierignore, .prettierrc.json, .secrets.baseline, jest.config.js, package-lock.json, package.json, tests/browser/step_definitions/intro.js, tests/browser/step_definitions/relying-party.js, tests/browser/support/setup.js, tests/unit/lib/helpers.js, tests/unit/src/app/kbv/controllers/load-question.test.js, tests/unit/src/lib/settings.test.js
Apply standardised repo config from other repos
- Update pre-commit hooks
- Remove a misconfigured Checkov hook
- Add an ESLint hook
- Address linting issues
- Use the prettier and jest plugins in ESLint
- Apply the recommended rules and styles for jest only for test files
- Install dev dependencies before running pre-commit to get ESLint plugins
- Allow unused variables if their names start with an underscore in test files
- Do linting as part of the pre-commit checks
- Update the linting commands
- Update the `.secrets.baseline` file to exclude specific keywords and files
- Update `package.json` to remove duplicated or unnecessary config
- Update linting and testing packages
=> OJ-1495: Update repo config

README.md, package-lock.json, package.json, tests/browser/package-lock.json, tests/browser/package.json, tests/imposter/README.md
Minor README and package updates
Just a couple of things I spotted while playing around
=> BAU Minor README and package updates

README.md, jest.config.js, sonar-project.properties
Ignore form-wizard config in sonar.properties
=> test: Add config filepaths to sonar.exclusions

package.json
=> pyic-4603: add jest watch

package-lock.json, package.json
- Update to 4.7 of govuk-frontend
- Update to latest version of hmpo packages
- breaking changes are all to do with dropping support for Node 12
=> chore: Update govuk-frontend and hmpo* packages

src/locales/cy/default.yml, src/locales/en/default.yml
Footer content and interactions changed to match standard journey behaviour
YAML content files have been updated.
Footer content should remain the same across the user journey to meet [the new **Consistent Help** WCAG 2.2 criteria](https://www.w3.org/WAI/WCAG22/Understanding/consistent-help).
=> CNUCD: Update footer content to standardise link text

.gitignore, README.md, package.json
Add debug script and update README
So we can run locally with debugger attached
=> chore: Add debug script

tests/browser/features/happy.feature, tests/imposter/data/questions.json, tests/imposter/private-api-config.yaml, tests/imposter/scripts/get-question.groovy, tests/imposter/scripts/post-answer.groovy
Refactored imposter script
- To allow us to create and test multiple and custom KBV journeys both locally and in the browser-test suite.
- To prevent journeys from interfering with each while testing
- [PYIC-4954](https://govukverify.atlassian.net/browse/PYIC-4954)
[PYIC-4954]: https://govukverify.atlassian.net/browse/PYIC-4954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PYIC-4954: Refactored imposter script

src/locales/cy/fields.yml, src/locales/en/fields.yml
Update radio button validation content
As a user, I want to be guided through the KBV questions with clear validations in place, so that I can prove my identity without making mistakes
- [PYIC-4916](https://govukverify.atlassian.net/browse/PYIC-4916)
[PYIC-4916]: https://govukverify.atlassian.net/browse/PYIC-4916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PYIC-4916: Update radio button validation content

src/locales/en/default.yml
Use the correct error summary title text. This applies to all error summary boxes
=> BAU: Update the error title text

tests/imposter/private-api-config.yaml
Imposter configuration
To not use undocumented behaviour
Change suggested by Pete Cornish. I have run the tests with this change and they still pass
=> BAU: Imposter config specifically handle the abandon journey.

src/app/kbv/controllers/load-question.js, src/app/kbv/controllers/self-assessment-payment-question.js, src/app/kbv/controllers/self-assessment-question.js, src/app/kbv/fields.js, src/app/kbv/steps.js, src/constants/question-keys.js, tests/unit/src/app/kbv/controllers/load-question.test.js, tests/unit/src/app/kbv/controllers/self-assessment-payment-question.test.js, tests/unit/src/app/kbv/controllers/self-assessment-question.test.js, tests/unit/src/app/kbv/controllers/single-amount-question.test.js, tests/unit/src/presenters/question-to-content.test.js, tests/unit/src/presenters/question-to-details.test.js, tests/unit/src/presenters/question-to-hint.test.js, tests/unit/src/presenters/question-to-inset.test.js, tests/unit/src/presenters/question-to-title.test.js, tests/unit/src/utils/tax-year-to-range.test.js
Created constants for questionKeys
This saves duplication and keeps things more consistent
=> BAU: Use constants for questionKeys

src/locales/cy/default.yml, src/locales/en/default.yml
Fix cookie banner translations
=> BAU: Fix cookie banner translations

deploy/template.yaml
Update CSLS destination to the new -2 destination
To align with the API in using the same destination
- [LIME-1109](https://govukverify.atlassian.net/browse/LIME-1109)
[LIME-1109]: https://govukverify.atlassian.net/browse/LIME-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1109 Update CSLS destination to the new -2 destination

deploy/template.yaml
Set GA4 related env vars in template
To enable GA4 tracking in deployed envs
- [PYIC-7328](https://govukverify.atlassian.net/browse/PYIC-7328)
[PYIC-7328]: https://govukverify.atlassian.net/browse/PYIC-7328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PYIC-7328 Set GA4 env vars

src/locales/cy/pages.yml, src/locales/en/fields.yml, src/locales/en/pages.yml, src/views/kbv/answer-security-questions.njk, src/views/kbv/self-assessment-router.njk
The design review was carried out by the UCD team and the following fixes were identified to the existing screens already developed. 
- [PYIC-7267](https://govukverify.atlassian.net/browse/PYIC-7267)
[PYIC-7267]: https://govukverify.atlassian.net/browse/PYIC-7267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PYIC-7267: UCD content fixes

CODEOWNERS
=> Remove orange as code owners

src/views/kbv/answer-security-questions.njk, src/views/kbv/pensions-benefits-self-assessment.njk, src/views/kbv/pensions-benefits-short-tax-return.njk, src/views/kbv/prove-identity-another-way.njk, src/views/kbv/self-assessment-payment.njk, src/views/kbv/self-assessment-router.njk, src/views/kbv/single-input-question.njk
Set GA4 content ids
- [PYIC-7190](https://govukverify.atlassian.net/browse/PYIC-7190)
[PYIC-7190]: https://govukverify.atlassian.net/browse/PYIC-7190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PYIC-7190: Set GA4 content ids

src/locales/cy/pages.yml
- Update Welsh translations for "If you have more than one P60 in a tax year" in line with UCD request
- UCD request
- [PYIC-7368](https://govukverify.atlassian.net/browse/PYIC-7368)
[PYIC-7368]: https://govukverify.atlassian.net/browse/PYIC-7368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PYIC-7368: Update Welsh translations for "If you have more than one P60 in a tax year"

deploy/template.yaml
- Reduce EcsStepScaleOutAlarm to 1 datapoint/1 period
- Lower MinAdjustmentMagnitude to 1 (to enable linear scaling)
- Align cooldowns to 60 second intervals (as alarm values only update every 60 seconds)
- EcsStepScaleInPolicy reduced cooldown to 180 (for faster reaction to any inital overscaling)
- EcsStepScaleOutPolicy increased cooldown to 180 (to avoid overscaling during traffic ramp)
- Change EcsStepScaleOutAlarm to fire at 60%
- Change EcsStepScaleInAlarm to fire at 20%
- Change EcsStepScaleOutPolicy first tier lower bound to 60%
- Change EcsStepScaleInPolicy reduce containers by -50%  at 20% traffic (40% after scaling in)
- Change EcsStepScaleInPolicy reduce containers by -90% at 5% traffic(50% after scaling in)
- Increase VCPUSize to act as a buffer as containers come online
- …
=> LIME-1316 - Adjust F.E scaling

deploy/template.yaml
Template.yaml updated as part of decommissioning of HMRC KBV to reduce maintenance costs. 
ECS Autoscaling min and max both set to one as without one container, the healthcheck will fail. CPU and memory set to minimum possible. Unnecessary alarms disabled.
- [LIME-1465](https://govukverify.atlassian.net/browse/LIME-1465)
I added the dev environment to the 'IsPerformance' condition and deployed to dev to test my changes. 
&nbsp;
**- Evidence min and max container value is working:**
&nbsp;
- **Evidence CPU and memory amended:**
post changes:
&nbsp;
&nbsp;
pre-changes:
&nbsp;
- **One container running:**
[LIME-1465]: https://govukverify.atlassian.net/browse/LIME-1465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1465 updates ECS configuration for decom

package-lock.json, package.json
Apply necessary security patches and updates to maintain a secure codebase
Updated the express dependency to address a vulnerable subdependency
patched version applied
- [LIME-1467](https://govukverify.atlassian.net/browse/LIME-1467)
[LIME-1467]: https://govukverify.atlassian.net/browse/LIME-1467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1467 applied security fixes
